- clean:
      ~/.config/hypr:
          recursive: true

- link:
        ~/.config/hypr:
              path: configs/hypr/*
        ~/.config/systemd/user/hyprland-session.target: configs/hypr/hyprland-session.target

- shell:
        - systemctl --user enable --now hyprland-session.target
