- clean:
      ~/.config/sway:
          recursive: true
      ~/.config/systemd/user/:

- link:
      ~/.config/sway/config: configs/sway/config
      ~/.config/sway/autostart: configs/sway/autostart
      ~/.config/sway/colors: configs/sway/colors
      ~/.config/sway/keyboard: configs/sway/keyboard
      ~/.config/sway/pointer: configs/sway/pointer
      ~/.config/sway/touchpad: configs/sway/touchpad
      ~/.config/sway/variables: configs/sway/variables
      ~/.config/systemd/user/sway-session.target: configs/sway/sway-session.target

- shell:
      - systemctl --user enable --now sway-session.target