- clean:
      ~/.zshenv:
      ~/.config/zsh:
          recursive: true

- link:
      ~/.zshenv: configs/zsh/zshenv
      ~/.config/zsh/.zshrc: configs/zsh/zshrc
      ~/.config/zsh/lib:
          path: configs/zsh/lib/*
