###########
### .zshrc
###########

### Configuration
typeset -g WORDCHARS=${WORDCHARS//\/[&.;]}
typeset -g ZLE_REMOVE_SUFFIX_CHARS=''
setopt correct
setopt extendedglob
setopt nocaseglob
setopt rcexpandparam
setopt nocheckjobs
setopt numericglobsort
setopt nobeep
setopt autocd

### Zim
# Set folder
ZIM_HOME=${ZDOTDIR}/zim
if [[ ! -r ${ZIM_HOME} ]]; then
    mkdir ${ZIM_HOME}
fi

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
  curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
      https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

# Initialize modules.
source ${ZIM_HOME}/init.zsh

### GPG agent
export GPG_TTY=$(tty)

### Sourcing
source $ZLIB/aliases.zsh
source $ZLIB/completion.zsh
source $ZLIB/history.zsh
source $ZLIB/keybindings.zsh
source $ZLIB/themes.zsh

# Start sway
if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
    cd ~
    export _JAVA_AWT_WM_NONREPARENTING=1
    export XCURSOR_SIZE=24
    exec Hyprland
fi

# SSH
export SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
