#!/bin/bash

### Brightness key handling in x11

notify() {
    brightness=$(echo "$(xbacklight -get)/1" | bc)
    bar=$(seq -s "●" $(( (brightness + 10) / 10 )) | sed 's/[0-9]//g')
    barempty=$(seq -s "○" $(( (110 - brightness) / 10)) | sed 's/[0-9]//g')

    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
    notify-send -u low -a $brightness -i display-brightness-symbolic.symbolic "$bar$barempty"
}

if [[ $1 == up ]]; then
    xbacklight -inc 10
    notify
elif [[ $1 == down ]]; then
    xbacklight -dec 10
    notify
else
    exit 0
fi
