#!/bin/bash

### Switcher for bluetooth headset profile between high quality audio (A2DP) and input/output (HSP/HFP)

SINK=$(pactl list sinks short | grep "bluez_output");
MAC_ADDRESS=$(echo "$SINK" | grep -oP '(?<=\.)\w+(?=\.)');
PROFILE=$(echo "$SINK" | grep -oP '(?<=\.)[\w-]+(?=\s)');

if [ "$SINK" ]; then
    case "$PROFILE" in
        a2dp-sink)
            pactl set-card-profile bluez_card."$MAC_ADDRESS" headset-head-unit
            notify-send -a "pacmd" "Switched to HSP/HFP"
            exit 0
        ;;
        headset-head-unit)
            pactl set-card-profile bluez_card."$MAC_ADDRESS" a2dp-sink
            notify-send -a "pacmd" "Switched to A2DP"
            exit 0
        ;;
        *)
            notify-send -a "pacmd" -u "critical" "Profile not recognized"
            exit 0
        ;;
    esac
else
    bluetooth-autoconnect
fi
