#!/bin/bash

### keyboard led handler

current_level=$(cat /sys/class/leds/asus::kbd_backlight/brightness)
all_levels=("off" "low" "med" "high")

notify() {
    paplay /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga
    notify-send -u low -a "Keyboard leds" -i display-brightness-symbolic.symbolic "$1"
}

if [[ $1 == up ]]; then
    next_level=$((current_level < 3 ? current_level + 1 : 3))
    asusctl -k "${all_levels[${next_level}]}"
    notify "${all_levels[${next_level}]}"
elif [[ $1 == down ]]; then
    next_level=$((current_level > 0 ? current_level -1 : 0))
    asusctl -k "${all_levels[${next_level}]}"
    notify "${all_levels[${next_level}]}"
elif [[ $1 == next ]]; then
    asusctl led-mode -n
    asusctl -k "${all_levels[${next_level}]}"
    notify "next mode"
else
    exit 0
fi
