#!/bin/sh

if pgrep -x "gtklock" > /dev/null
then
    exit
fi

OUTPUTS=$(hyprctl -j monitors | jq --raw-output '.[] .name')

for OUTPUT in $OUTPUTS
do
	grim -o "$OUTPUT" "/tmp/$OUTPUT.png"
	corrupter -mag 4 "/tmp/$OUTPUT.png" "/tmp/$OUTPUT.png"
	convert -brightness-contrast -10x10 "/tmp/$OUTPUT.png" "/tmp/$OUTPUT.png" &
done
wait
exec gtklock -di -s ~/.config/gtklock/style.css "$@"
