#!/bin/sh

OUTPUTS=$(swaymsg --type get_outputs --raw | jq --raw-output '.[] |select(.active) | .name')

for OUTPUT in $OUTPUTS
do
	grim -o "$OUTPUT" "/tmp/$OUTPUT.png"
	corrupter -mag 4 "/tmp/$OUTPUT.png" "/tmp/$OUTPUT.png"
	convert -brightness-contrast -10x10 "/tmp/$OUTPUT.png" "/tmp/$OUTPUT.png" &
done
wait
exec gtklock -d -s ~/.config/gtklock/style.css "$@"
