#!/bin/bash

### Mouse-warping fix for i3/X11

XDT=/usr/bin/xdotool

WINDOW=`$XDT getwindowfocus`

# this brings in variables WIDTH and HEIGHT
eval `xdotool getwindowgeometry --shell $WINDOW`

if [ $X -gt 0 ] && [ $Y -gt 0 ]
then
    TX=`expr $WIDTH / 2`
    TY=`expr $HEIGHT / 2`
    $XDT mousemove -window $WINDOW $TX $TY
fi
