#!/bin/bash

CHOICE=$1
DIR=${SCREENSHOT_DIR:=$HOME/pictures/screenshots}

mkdir -p "$DIR"

case $CHOICE in
    area) grim -g "$(slurp -d)" - | swappy -f -;;
    focused) grim -g "$(hyprctl -j activewindow | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')" - | swappy -f -;;
    output) grim -o "$(hyprctl -j monitors | jq -r '.[] | select(.focused) | .name')" - | swappy -f -;;
    screen) grim - | swappy -f -;;
esac

