#!/usr/bin/env bash

### Window focus switcher for sway

windows=$(swaymsg -t get_tree | jq -r 'recurse(.nodes[]?)|recurse(.floating_nodes[]?)|select(.type=="con"),select(.type=="floating_con")|(.id|tostring)+" "+.app_id+": "+.name')

selected=$(echo "$windows" | rofi -dmenu -i | awk '{print $1}')

swaymsg [con_id="$selected"] focus
